vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        school_logo:
            upload_destination: '%kernel.share_dir%/files/school/logo'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: 'id'
