services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      target: frankenphp_dev
    volumes:
      - .:/app
      - ~/.composer:/composer:z
      - caddy_config:/config
      - caddy_data:/data
      - ./docker/web/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./docker/web/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    depends_on:
      - database
    environment:
      #frankenphp config
      SERVER_NAME: localhost
      COMPOSER_HOME: /composer
      XDEBUG_MODE: off
      FRANKENPHP_WORKER_CONFIG: watch
      PHP_IDE_CONFIG: serverName=backend
      #symfony
      DATABASE_URL: postgresql://yesman:yesman@database:5432/yesman?serverVersion=18&charset=utf8
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: yesman
      POSTGRES_PASSWORD: yesman
      POSTGRES_DB: yesman
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  worker:
    scale: 2
    profiles:
      - donotstart
    build:
      dockerfile: docker/web/Dockerfile
      target: frankenphp_dev
    restart: unless-stopped
    environment:
      WORKER: true
    healthcheck:
      disable: false
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./:/app

volumes:
  postgres_data: {}
  caddy_config: {}
  caddy_data: {}
