<?php

namespace App\Enum;

enum SchoolScope: string
{
    case MANAGE_STUDENTS = 'MANAGE_STUDENTS';
    case MANAGE_PROGRAMS = 'MANAGE_PROGRAMS';
    case MANAGE_PROSPECTS = 'MANAGE_PROSPECTS';
    case MANAGER_FINANCE = 'MANAGER_FINANCE';
    case MANAGE_COMMUNICATIONS = 'MANAGE_COMMUNICATIONS';
}
